from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Class)
admin.site.register(Subject)
admin.site.register(Room)
admin.site.register(Teacher)
admin.site.register(Student)
admin.site.register(Parent)
admin.site.register(TeacherAttendance)
admin.site.register(StudentAttendance)
admin.site.register(TeacherSalary)
admin.site.register(TeacherSalaryHistory)
admin.site.register(Exam)
admin.site.register(StudentExam)
admin.site.register(ExamGrade)
admin.site.register(ExamTemporary)
admin.site.register(StudentGrade)
admin.site.register(EventCategory)
admin.site.register(EventCategoryType)
admin.site.register(Event)
admin.site.register(StudentPayment)
admin.site.register(StudentPaymentHistory)
admin.site.register(PaymentRatifications)
admin.site.register(Chat)
admin.site.register(GroupMessage)
admin.site.register(MyFriends)
admin.site.register(MainNotification)
admin.site.register(NotificationHistory)
admin.site.register(OnlineChat)
admin.site.register(CriticalHistory)
admin.site.register(Temporary)
admin.site.register(SubjectRoutine)
